# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYCVQ3Wd1J-icMhGHaxiI_BldVGi-Nhc
"""

import os
import mmap
import re

def extract_logs(log_file, target_date, output_dir="output"):
    if not os.path.exists(log_file):
        print(f"Error: Log file '{log_file}' not found.")
        return

    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, f"output_{target_date}.txt")

    date_pattern = re.compile(f"^{target_date} ")

    with open(log_file, "r", encoding="utf-8", errors="ignore") as f:
        with mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ) as mm:
            with open(output_file, "w", encoding="utf-8") as out:
                for line in iter(mm.readline, b""):
                    decoded_line = line.decode("utf-8", errors="ignore")
                    if date_pattern.match(decoded_line):
                        out.write(decoded_line)

    print(f"Logs for {target_date} have been extracted to {output_file}")

# Specify the correct path
log_file_path = "/content/drive/MyDrive/logs_folder/logs_2024.log"  # Adjust this path
target_date = "2024-12-01"  # Change the date you want to extract

extract_logs(log_file_path, target_date)